# Generated by Django 3.1.7 on 2021-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210524_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
