# Generated by Django 3.1.7 on 2021-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210524_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='posts',
            name='thumb_nail',
            field=models.FileField(null=True, upload_to='posts/'),
        ),
    ]
